[workspace]
# exclude = ["benches"]

members = [
    "crates/osm_reader",
    "crates/frontend/src-tauri",
    "crates/ch_core",
    "crates/repl",
    "benches",
]

[profile.release]
lto = "fat"
panic = "abort"
