[workspace]
exclude = ["benches"]

members = [
    "crates/osm_reader",
    "crates/frontend/src-tauri",
    "crates/ch_core",
    "crates/repl",
    "crates/graph_viz_macroquad",
    "crates/ggez-test",
]

[profile.release]
lto = "fat"
panic = "abort"
codegen-units = 1
