[workspace]
exclude = ["benches"]

members = [
    "crates/osm_reader",
    "crates/ch_core",
    "crates/repl",
    "crates/graph_viz",
]

[profile.release]
lto = "fat"
panic = "abort"
codegen-units = 1
