[package]
name = "osm_reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
osmpbf = "0.3.0"
rustc-hash = "1.1.0"
log = "0.4.17"


[[bench]]
name = "simplify"
harness = false
